### ISSUE TITLE
Django 2.1: django.db.models.permalink() removed

### ISSUE THREAD

**Issue by v-gar** [danirus/django-comments-xtd#104]
I tried to update my Django application (which uses django-comments-xtd) to Django 2.1.

At the moment I get the following error:
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1a1e41c1e0>
Traceback (most recent call last):
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/me/mydjangoapp/blog/models.py", line 6, in <module>
    from django_comments_xtd.moderation import moderator, SpamModerator
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments_xtd/moderation.py", line 14, in <module>
    from django_comments.moderation import Moderator, CommentModerator
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments/moderation.py", line 369, in <module>
    moderator = Moderator()
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments/moderation.py", line 294, in __init__
    self.connect()
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments/moderation.py", line 302, in connect
    signals.comment_will_be_posted.connect(self.pre_save_moderation, sender=django_comments.get_model())
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments/__init__.py", line 47, in get_model
    return get_comment_app().get_model()
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments_xtd/__init__.py", line 13, in get_model
    return import_string(settings.COMMENTS_XTD_MODEL)
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments_xtd/models.py", line 63, in <module>
    class XtdComment(Comment):
  File "/home/me/mydjangoapp/.env/lib/python3.7/site-packages/django_comments_xtd/models.py", line 110, in XtdComment
    @models.permalink
AttributeError: module 'django.db.models' has no attribute 'permalink'
```
I guess the error belongs to Django Comments XTD.

Can the others reproduce a similar error? Django==2.0.8 works flawlessly - Django==2.1 not.

I looked up the [2.1 changelog](https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1) and discovered the following removement: 

> The django.db.models.permalink() decorator is removed.

**Comment by danirus** [comment]
Hi @v-gar, it's not a bug in django-comments-xtd, just a lack of support for Django v2.1.
I've just added it in the branch `support-django-2.1`. 
Maybe you could give it a try before I merge it. 
I will do it myself later today.

**Comment by 42force** [comment]
> `support-django-2.1`.

Hi where do you add the support-django 2.1?

**Comment by 52lemon** [comment]
i got the same error in django 2.2.4
`
 @models.permalink
AttributeError: module 'django.db.models' has no attribute 'permalink'
`

**Comment by danirus** [comment]
@42force, @52lemon, I can't reproduce the error. 
Could you build a small example showing the case?
@52lemon, django-comments-xtd doesn't use the permalink decorator.
