### ISSUE TITLE
Exception in thread django-main-thread: … KeyError: 'django'

### ISSUE THREAD

**Issue by yhoiseth** [danirus/django-comments-xtd#133]
Trying to set up the `comp` example as instructed on https://django-comments-xtd.readthedocs.io/en/latest/example.html#setup, I get the following error:

```
(.venv) ➜  comp git:(131-norwegian) python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/contrib/admin/checks.py", line 79, in check_dependencies
    for engine in engines.all():
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/backends/django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/backends/django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/backends/django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/rest_framework/templatetags/rest_framework.py", line 12, in <module>
    from rest_framework.renderers import HTMLFormRenderer
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/rest_framework/renderers.py", line 19, in <module>
    from django.test.client import encode_multipart
  File "/Users/yngve/Repositories/yhoiseth/django-comments-xtd/.venv/lib/python3.7/site-packages/django/test/client.py", line 23, in <module>
    from django.test import signals
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 149, in __enter__
  File "<frozen importlib._bootstrap>", line 94, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('django.test.signals') at 4440018576
```

Note that I'm using `venv` because I'm unsure about how to use `virtualenv` with my setup.

# System information

- macOS Mojave 10.14.6 (18G1012)
- Python 3.7.5
- Django 2.2.7

I suspect that the issue is related to Python and/or Django versions. I'll try to create a CI build with these versions to see if that's correct.

**Comment by yhoiseth** [comment]
Hmm… Considering that #134 passed, I don't think Python 3.7 is to blame. In case it helps, here's the entire output of `pip freeze`:

```
certifi==2019.9.11
chardet==3.0.4
Django==2.2.7
django-comments-xtd==2.4.1
django-contrib-comments==1.9.1
django-markdown2==0.3.1
-e git+ssh://git@github.com/mbi/django-rosetta.git@3c249d344eaf667b58a61a0433d65fb2a8c72355#egg=django_rosetta
djangorestframework==3.9.0
docutils==0.15.2
idna==2.8
markdown2==2.3.8
polib==1.1.0
pytz==2019.3
requests==2.22.0
six==1.13.0
sqlparse==0.3.0
urllib3==1.25.6
```

**Comment by danirus** [comment]
Hi @yhoiseth, sorry for this very late reply.
Did you manage to run the comp project?
I don't think the issue had anything to do with the version of Python or Django.
Just in case you wanted to give it a try with Docker, [here](https://github.com/danirus/docker-django-comments-xtd-demo) is the Dockerfile.

**Comment by yhoiseth** [comment]
Hi @danirus,

No problem. We went with another solution, so you I’m closing this.
