### ISSUE TITLE
PyPi Package is different?

### ISSUE THREAD

**Issue by cadu-leite** [danirus/django-comments-xtd#27]
I have django-comment installed 

    $pip freeze 
    ...
    django-comments-xtd==1.2
    django-contrib-comments==1.6.1
    ...

I've inatalled comments-xtd using PyPi.

    $sudo pip install django-comments-xtd==1.2

But I got an  _import error_ trying to start my app. (trace back above)

seems the pypi package diffs from the repository, 
althought the last package is equal to the last commit .

the `models.py` I have on my environment, installed from _pypi_

    from django.db import models, transaction
    from django.db.models import F, Max, Min
    from django.contrib.comments.models import Comment
    from django.contrib.contenttypes.models import ContentType
    from django.utils.safestring import mark_safe
    from django.utils.translation import ugettext, ugettext_lazy as _
    from django_comments_xtd.conf import settings

## Entire traceback

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
        django.setup()
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
        module = import_module(entry)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django_comments_xtd/__init__.py", line 1, in <module>
        from django_comments_xtd.models import XtdComment
      File "/Users/cadu/.virtualenvs/treeio_dj18/lib/python2.7/site-packages/django_comments_xtd/models.py", line 5, in <module>
        from django.contrib.comments.models import Comment
    ImportError: No module named comments.models

**Comment by cadu-leite** [comment]
after install from github, the error has no more .

$>pip install -e git+git@github.com:danirus/django-comments-xtd.git#egg=django-comments-xtd

**Comment by danirus** [comment]
Thank you for reporting it, @cadu-leite. I'm sorry I didn't reply earlier. 
The current package available in PyPI, which is the v1.5.1, should work without problems in Django versions from 1.4 to v1.9. 

For the following major release the code in master won't work in versions of Django older than v1.8. Bare in mind this if you don't update Django very often. In such a case it would be better to stick to specific versions rather using the git url.
