### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by bufke** [danirus/django-comments-xtd#30]
We get a rather unhelpful traceback

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 176, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python3.4/functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/local/lib/python3.4/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Reproduced with a brand new django 1.9 project and adding comments xtd. I think 1.9 doesn't allow you to access models at startup.

**Comment by danirus** [comment]
Hi @bufke, thanks for telling.
I will look into it soon.

**Comment by danirus** [comment]
Sorry for the delay @bufke,
Fixed in https://github.com/danirus/django-comments-xtd/commit/c94afb0511d305d5c5d3b908afcde66eec960eaa.
