### ISSUE TITLE
Crash when using postgres sql

### ISSUE THREAD

**Issue by sanastasiou** [danirus/django-comments-xtd#93]
[2018-03-21 14:58:09 +0100] [8902] [DEBUG] POST /comments/api/comment/
Internal Server Error: /comments/api/comment/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: invalid input syntax for type inet: "b''"
LINE 1: ... '2018-03-21T13:58:09.673411+00:00'::timestamptz, 'b'''''::i...
                                                             ^

The above exception was the direct cause of the following exception:

                                                                                                                                                                                          5715,1        98%
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/api/views.py", line 22, in post
    response = super(CommentCreate, self).post(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/generics.py", line 192, in post
    return self.create(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/api/views.py", line 32, in perform_create
    self.resp_dict = serializer.save()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/api/serializers.py", line 146, in save
    new_comment = views._create_comment(resp['comment'])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/views.py", line 90, in _create_comment
    comment.save()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/models.py", line 74, in save
    super(Comment, self).save(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments/abstracts.py", line 98, in save
    super(CommentAbstractModel, self).save(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 836, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 863, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
                                                                                                                                                                                          5764,1        99%
    response = self.handle_exception(exc)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/api/views.py", line 22, in post
    response = super(CommentCreate, self).post(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/generics.py", line 192, in post
    return self.create(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/api/views.py", line 32, in perform_create
    self.resp_dict = serializer.save()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/api/serializers.py", line 146, in save
    new_comment = views._create_comment(resp['comment'])
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/views.py", line 90, in _create_comment
    comment.save()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments_xtd/models.py", line 74, in save
    super(Comment, self).save(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django_comments/abstracts.py", line 98, in save
    super(CommentAbstractModel, self).save(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 836, in save_base
    self._save_parents(cls, using, update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 863, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/utils.py", line 94, in _exit_
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: invalid input syntax for type inet: "b''"
LINE 1: ... '2018-03-21T13:58:09.673411+00:00'::timestamptz, 'b'''''::i...

**Comment by sanastasiou** [comment]
@danirus could you please post your postgre SQL settings here?

**Comment by sanastasiou** [comment]
Actually this is the issue exactly:

https://github.com/django/django-contrib-comments/issues/93

Comp project failed with the exact same error. I guess we need some of the mentioned workarounds.

**Comment by danirus** [comment]
Thanks for the link @sanastasiou. 
It's not a problem of this app though.
I think it would be worth mentioning in the documentation.

**Comment by sanastasiou** [comment]
@danirus  Can you update your dependencies to use the latest release of this:

package? https://github.com/django/django-contrib-comments

The bug is already fixed with this commit:

https://github.com/django/django-contrib-comments/commit/cb50604156af15486931732a6593b47abca75efe

**Comment by danirus** [comment]
Hi @sanastasiou, they have to roll out a new release to include that commit, django-comments-xtd will pick it automatically (unless it is a major release, like 2.x). So no need to change anything here.

That way you pick django-contrib-comments from the master branch instead of picking the package from PyPI. Add this line to your requirements file to do so:

    -e git+git://github.com/django/django-contrib-comments.git#egg=django-comments

The project is very stable, but theoretically it's a risk. Using the master you may get commits that belong to a major release change, and those could eventually break compatibility.

**Comment by sanastasiou** [comment]
`class BaseMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):      
        if request.META['REMOTE_ADDR'] == 'b\'\'':
            request.META['REMOTE_ADDR'] = ''

        return self.get_response(request)`

**Comment by sanastasiou** [comment]
This is the real solution to the bug. Even the latest django contrib comments doesn't fix this. But this little middleware does.

**Comment by danirus** [comment]
Thanks @sanastasiou
